### ISSUE TITLE
Just is Rust not Go

### ISSUE THREAD

**Issue by runeimp** [pyrsmk/run#2]
Hey there, wanted to let you know that "Just (the Go project)" should be "Just (written in Rust)", or similar, as it is actually written in Rust and saying "the Rust project" would likely ruffle the feathers of The Rust Project or the Rust Foundation as it is not affiliated with either organization but _might_ sound like it is with the former. And it seems such things are likely a matter of great importance to both orgs. I don't care but wanted to warn you, just in case. 😉

**Comment by pyrsmk** [comment]
Indeed. Thanks for the correction !
